---

version: '2'
services:
  ui:
    image: edhenry/chexnet-jupyter:latest
    networks: 
      kafka_data-stack-net:
        ipv4_address: 172.23.0.20
    entrypoint: [jupyter, notebook, --allow-root]
    environment:
      JUPYTER_TOKEN: "demo"

# TODO : custom linkage between docker-compose files for NiFi and Kafka
# Need to break this out into separate logic at some point or another
networks: 
    kafka_data-stack-net:
        external: true