---

version: '2'
services:
  ui:
    image: edhenry/xray-webapp:latest
    ports:
      - "9220"
    networks:
      kafka_data-stack-net:
        ipv4_address: 172.23.0.8
    
networks: 
    kafka_data-stack-net:
        external: true