---

version: '2'
services:
  xraywebapp:
    image: edhenry/xray-webapp
    ports:
      - "9220"
    networks:
      - kafka_data-stack-net
    
networks: 
    kafka_data-stack-net:
        external: true